name: CI/CD to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'                # set this to the node version to use

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Run npm install, build, and test
      working-directory: ./src
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: react-app
        path: |
          ./src/build/client

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: react-app

    - name: Deploy static site to AWS (S3+CDN+R53)
      uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.6
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: us-east-1

        checkout: false
        aws_site_source_folder: .

        tf_action: 'apply'
        tf_state_bucket_destroy: true # If destroying, will remove the bucket
        tf_state_bucket: reelpedia-prod-tf-state

        # Enable with route53 to deploy with TLS
        aws_site_cdn_enabled: true

        # Deploy to www.reelpedia.com
        aws_r53_domain_name: reelpedia.com
        aws_r53_sub_domain_name: www
        aws_r53_create_sub_cert: true

        aws_site_bucket_name: www