# Build, test and deploy Reelpedia to Github Pages
name: CI/CD to Github Pages PROD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Run npm install, build, and test
      working-directory: ./src
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: react-app
        path: |
          ./src/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: react-app
        path: ./src/build

    - name: Display structure of downloaded files
      run: ls -R

    - name: Configure git
      working-directory: ./src
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git remote set-url origin https://oauth:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

    - name: Deploy to Github Pages
      working-directory: ./src
      run: |
        npm install
        npm run deploy
